"""migracion inicial completa

Revision ID: 6308f60ca981
Revises: 
Create Date: 2026-03-22 08:50:26.317675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6308f60ca981'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS gmi")
    op.execute("CREATE SCHEMA IF NOT EXISTS gmi_catalogo")
    op.execute("CREATE SCHEMA IF NOT EXISTS gmi_auth")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_categoria_educativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icono', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='gmi_auth'
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='gmi_auth'
    )
    op.create_table('cat_diagnostico_cie10',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_eapb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('regimen', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_estado_nutricional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_grupo_poblacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_hemoclasificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_metodo_anticonceptivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_micronutriente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_modulo_clinico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('semana_eg_inicio', sa.Integer(), nullable=True),
    sa.Column('semana_eg_fin', sa.Integer(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_nacionalidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_pertenencia_etnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_prioridad_alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color_hex', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('requiere_accion_inmediata', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_tipo_alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_tipo_ecografia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_tipo_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('unidad', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_tipo_profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('cat_vacuna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dosis_esperadas', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_catalogo'
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=True),
    sa.Column('semana_eg', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['gmi_catalogo.cat_modulo_clinico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('rol_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['gmi_auth.permiso.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['gmi_auth.rol.id'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso'),
    schema='gmi_auth'
    )
    op.create_table('usuario_staff',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('ips_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ips_id'], ['gmi_catalogo.cat_ips.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['gmi_auth.rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='gmi_auth'
    )
    op.create_table('carga_excel',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archivo_nombre', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('total_gestantes', sa.Integer(), nullable=True),
    sa.Column('nuevas', sa.Integer(), nullable=True),
    sa.Column('actualizadas', sa.Integer(), nullable=True),
    sa.Column('errores', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['gmi_auth.usuario_staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('contenido_educativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_contenido', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('cuerpo_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url_recurso', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('url_imagen', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('modulo_id', sa.Integer(), nullable=True),
    sa.Column('semana_eg_inicio', sa.Integer(), nullable=True),
    sa.Column('semana_eg_fin', sa.Integer(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['gmi.cat_categoria_educativa.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['modulo_id'], ['gmi_catalogo.cat_modulo_clinico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('gestante',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_gmi', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('nacionalidad_id', sa.Integer(), nullable=True),
    sa.Column('eapb_id', sa.Integer(), nullable=True),
    sa.Column('pertenencia_etnica_id', sa.Integer(), nullable=True),
    sa.Column('grupo_poblacional_id', sa.Integer(), nullable=True),
    sa.Column('tipo_regimen', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('fecha_ultima_menstruacion', sa.Date(), nullable=False),
    sa.Column('fecha_probable_parto', sa.Date(), nullable=True),
    sa.Column('anio_ingreso', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso_cpn', sa.Date(), nullable=True),
    sa.Column('semanas_eg_ingreso', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('modulo_activo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['eapb_id'], ['gmi_catalogo.cat_eapb.id'], ),
    sa.ForeignKeyConstraint(['grupo_poblacional_id'], ['gmi_catalogo.cat_grupo_poblacional.id'], ),
    sa.ForeignKeyConstraint(['modulo_activo_id'], ['gmi_catalogo.cat_modulo_clinico.id'], ),
    sa.ForeignKeyConstraint(['nacionalidad_id'], ['gmi_catalogo.cat_nacionalidad.id'], ),
    sa.ForeignKeyConstraint(['pertenencia_etnica_id'], ['gmi_catalogo.cat_pertenencia_etnica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_gmi'),
    schema='gmi'
    )
    op.create_table('pregunta_seguimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto_pregunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_respuesta', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=True),
    sa.Column('frecuencia', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('es_signo_alarma', sa.Boolean(), nullable=False),
    sa.Column('prioridad_alerta_default_id', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['modulo_id'], ['gmi_catalogo.cat_modulo_clinico.id'], ),
    sa.ForeignKeyConstraint(['prioridad_alerta_default_id'], ['gmi_catalogo.cat_prioridad_alerta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('antecedente_patologico',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_condicion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_diagnostico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('controlada', sa.Boolean(), nullable=True),
    sa.Column('tratamiento_actual', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('anticoncepcion_posparto',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metodo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['metodo_id'], ['gmi_catalogo.cat_metodo_anticonceptivo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('carga_excel_detalle',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('carga_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fila_numero', sa.Integer(), nullable=False),
    sa.Column('hoja', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mensaje_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['gmi.carga_excel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('chat_ia',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('checklist_gestante',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['gmi.checklist_item.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('cita_medica',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ips_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_cita', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['ips_id'], ['gmi_catalogo.cat_ips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('consentimiento_informado',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash_consentimiento', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_aceptacion', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('control_prenatal',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_control', sa.Integer(), nullable=False),
    sa.Column('fecha_control', sa.Date(), nullable=False),
    sa.Column('semana_gestacion', sa.Integer(), nullable=False),
    sa.Column('ips_id', sa.Integer(), nullable=True),
    sa.Column('tipo_profesional_id', sa.Integer(), nullable=True),
    sa.Column('tipo_consulta', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['ips_id'], ['gmi_catalogo.cat_ips.id'], ),
    sa.ForeignKeyConstraint(['tipo_profesional_id'], ['gmi_catalogo.cat_tipo_profesional.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('ecografia',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_ecografia_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('semana_gestacion', sa.Integer(), nullable=True),
    sa.Column('resultado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan_manejo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['tipo_ecografia_id'], ['gmi_catalogo.cat_tipo_ecografia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('evaluacion_salud_mental',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrumento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('recomendaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('formula_obstetrica',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestaciones', sa.Integer(), nullable=False),
    sa.Column('partos', sa.Integer(), nullable=False),
    sa.Column('cesareas', sa.Integer(), nullable=False),
    sa.Column('abortos', sa.Integer(), nullable=False),
    sa.Column('vivos', sa.Integer(), nullable=False),
    sa.Column('mortinatos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gestante_id'),
    schema='gmi'
    )
    op.create_table('historial_modulo',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modulo_anterior_id', sa.Integer(), nullable=True),
    sa.Column('modulo_nuevo_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origen', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['modulo_anterior_id'], ['gmi_catalogo.cat_modulo_clinico.id'], ),
    sa.ForeignKeyConstraint(['modulo_nuevo_id'], ['gmi_catalogo.cat_modulo_clinico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('notificacion',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado_entrega', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('opcion_pregunta_seguimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('texto_opcion', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('valor_numerico', sa.Integer(), nullable=True),
    sa.Column('es_alarma', sa.Boolean(), nullable=False),
    sa.Column('prioridad_alerta_id', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_id'], ['gmi.pregunta_seguimiento.id'], ),
    sa.ForeignKeyConstraint(['prioridad_alerta_id'], ['gmi_catalogo.cat_prioridad_alerta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('parto',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_parto', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_parto', sa.Date(), nullable=False),
    sa.Column('complicaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uci_materna', sa.Boolean(), nullable=False),
    sa.Column('muerte_materna', sa.Boolean(), nullable=False),
    sa.Column('causa_muerte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_muerte', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gestante_id'),
    schema='gmi'
    )
    op.create_table('perfil_clinico',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enfermedades_cronicas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alergias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('habitos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condiciones_riesgo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gestante_id'),
    schema='gmi'
    )
    op.create_table('pregunta_educativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido_id', sa.Integer(), nullable=False),
    sa.Column('texto_pregunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_pregunta', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contenido_id'], ['gmi.contenido_educativo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('pregunta_seguridad',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pregunta', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('hash_respuesta', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gestante_id'),
    schema='gmi'
    )
    op.create_table('progreso_educativo',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contenido_id', sa.Integer(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contenido_id'], ['gmi.contenido_educativo.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('puerperio',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dias_posparto', sa.Integer(), nullable=False),
    sa.Column('fecha_evaluacion', sa.Date(), nullable=False),
    sa.Column('complicaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('remision_interdisciplinaria',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.Column('fecha_remision', sa.Date(), nullable=False),
    sa.Column('fecha_atencion', sa.Date(), nullable=True),
    sa.Column('semana_gestacion', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['especialidad_id'], ['gmi_catalogo.cat_especialidad.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('sintoma_reportado',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modulo_origen', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severidad', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('suministro_micronutriente',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('micronutriente_id', sa.Integer(), nullable=False),
    sa.Column('suministrado', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['micronutriente_id'], ['gmi_catalogo.cat_micronutriente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('vacunacion',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vacuna_id', sa.Integer(), nullable=False),
    sa.Column('dosis', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['vacuna_id'], ['gmi_catalogo.cat_vacuna.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('audit_log',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tabla_afectada', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('registro_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['gmi_auth.usuario_staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi_auth'
    )
    op.create_table('clasificacion_riesgo',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_prenatal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_riesgo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('nivel', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('clasificacion_ia', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('diagnostico_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('situaciones_biosicosocial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('explicacion_ia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_evaluacion', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['control_prenatal_id'], ['gmi.control_prenatal.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('examen_laboratorio',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_prenatal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_examen_id', sa.Integer(), nullable=False),
    sa.Column('fecha_toma', sa.Date(), nullable=False),
    sa.Column('resultado', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resultado_numerico', sa.Numeric(), nullable=True),
    sa.Column('unidad', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('trimestre', sa.Integer(), nullable=True),
    sa.Column('semana_gestacion', sa.Integer(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['control_prenatal_id'], ['gmi.control_prenatal.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['tipo_examen_id'], ['gmi_catalogo.cat_tipo_examen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('opcion_respuesta_educativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('texto_opcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_id'], ['gmi.pregunta_educativa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('recien_nacido',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parto_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vivo', sa.Boolean(), nullable=False),
    sa.Column('peso_gramos', sa.Float(), nullable=True),
    sa.Column('talla_cm', sa.Float(), nullable=True),
    sa.Column('uci_neonatal', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parto_id'], ['gmi.parto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('respuesta_seguimiento',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('respuesta_booleana', sa.Boolean(), nullable=True),
    sa.Column('respuesta_numerica', sa.Integer(), nullable=True),
    sa.Column('opcion_id', sa.Integer(), nullable=True),
    sa.Column('semana_gestacion', sa.Integer(), nullable=True),
    sa.Column('alerta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['opcion_id'], ['gmi.opcion_pregunta_seguimiento.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['gmi.pregunta_seguimiento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('signos_vitales',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_prenatal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('talla_cm', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('estado_nutricional_id', sa.Integer(), nullable=True),
    sa.Column('altura_uterina', sa.Float(), nullable=True),
    sa.Column('presion_sistolica', sa.Integer(), nullable=True),
    sa.Column('presion_diastolica', sa.Integer(), nullable=True),
    sa.Column('fcf', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['control_prenatal_id'], ['gmi.control_prenatal.id'], ),
    sa.ForeignKeyConstraint(['estado_nutricional_id'], ['gmi_catalogo.cat_estado_nutricional.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_prenatal_id'),
    schema='gmi'
    )
    op.create_table('alerta',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clasificacion_riesgo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_alerta_id', sa.Integer(), nullable=False),
    sa.Column('prioridad_id', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('modulo_origen', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resuelta_por', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clasificacion_riesgo_id'], ['gmi.clasificacion_riesgo.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['prioridad_id'], ['gmi_catalogo.cat_prioridad_alerta.id'], ),
    sa.ForeignKeyConstraint(['resuelta_por'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['tipo_alerta_id'], ['gmi_catalogo.cat_tipo_alerta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('respuesta_educativa_gestante',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('opcion_seleccionada_id', sa.Integer(), nullable=True),
    sa.Column('es_correcta', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['opcion_seleccionada_id'], ['gmi.opcion_respuesta_educativa.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['gmi.pregunta_educativa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('llamada_emergencia',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alerta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('destino', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('duracion_seg', sa.Integer(), nullable=True),
    sa.Column('resultado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['gmi.alerta.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('referencia',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alerta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ips_origen_id', sa.Integer(), nullable=True),
    sa.Column('ips_destino_id', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_referencia', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['gmi.alerta.id'], ),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.ForeignKeyConstraint(['ips_destino_id'], ['gmi_catalogo.cat_ips.id'], ),
    sa.ForeignKeyConstraint(['ips_origen_id'], ['gmi_catalogo.cat_ips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gmi'
    )
    op.create_table('contrareferencia',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referencia_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('respuesta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnostico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indicaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_atencion', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referencia_id'], ['gmi.referencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia_id'),
    schema='gmi'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrareferencia', schema='gmi')
    op.drop_table('referencia', schema='gmi')
    op.drop_table('llamada_emergencia', schema='gmi')
    op.drop_table('respuesta_educativa_gestante', schema='gmi')
    op.drop_table('alerta', schema='gmi')
    op.drop_table('signos_vitales', schema='gmi')
    op.drop_table('respuesta_seguimiento', schema='gmi')
    op.drop_table('recien_nacido', schema='gmi')
    op.drop_table('opcion_respuesta_educativa', schema='gmi')
    op.drop_table('examen_laboratorio', schema='gmi')
    op.drop_table('clasificacion_riesgo', schema='gmi')
    op.drop_table('audit_log', schema='gmi_auth')
    op.drop_table('vacunacion', schema='gmi')
    op.drop_table('suministro_micronutriente', schema='gmi')
    op.drop_table('sintoma_reportado', schema='gmi')
    op.drop_table('remision_interdisciplinaria', schema='gmi')
    op.drop_table('puerperio', schema='gmi')
    op.drop_table('progreso_educativo', schema='gmi')
    op.drop_table('pregunta_seguridad', schema='gmi')
    op.drop_table('pregunta_educativa', schema='gmi')
    op.drop_table('perfil_clinico', schema='gmi')
    op.drop_table('parto', schema='gmi')
    op.drop_table('opcion_pregunta_seguimiento', schema='gmi')
    op.drop_table('notificacion', schema='gmi')
    op.drop_table('historial_modulo', schema='gmi')
    op.drop_table('formula_obstetrica', schema='gmi')
    op.drop_table('evaluacion_salud_mental', schema='gmi')
    op.drop_table('ecografia', schema='gmi')
    op.drop_table('control_prenatal', schema='gmi')
    op.drop_table('consentimiento_informado', schema='gmi')
    op.drop_table('cita_medica', schema='gmi')
    op.drop_table('checklist_gestante', schema='gmi')
    op.drop_table('chat_ia', schema='gmi')
    op.drop_table('carga_excel_detalle', schema='gmi')
    op.drop_table('anticoncepcion_posparto', schema='gmi')
    op.drop_table('antecedente_patologico', schema='gmi')
    op.drop_table('pregunta_seguimiento', schema='gmi')
    op.drop_table('gestante', schema='gmi')
    op.drop_table('contenido_educativo', schema='gmi')
    op.drop_table('carga_excel', schema='gmi')
    op.drop_table('usuario_staff', schema='gmi_auth')
    op.drop_table('rol_permiso', schema='gmi_auth')
    op.drop_table('checklist_item', schema='gmi')
    op.drop_table('cat_vacuna', schema='gmi_catalogo')
    op.drop_table('cat_tipo_profesional', schema='gmi_catalogo')
    op.drop_table('cat_tipo_examen', schema='gmi_catalogo')
    op.drop_table('cat_tipo_ecografia', schema='gmi_catalogo')
    op.drop_table('cat_tipo_alerta', schema='gmi_catalogo')
    op.drop_table('cat_prioridad_alerta', schema='gmi_catalogo')
    op.drop_table('cat_pertenencia_etnica', schema='gmi_catalogo')
    op.drop_table('cat_nacionalidad', schema='gmi_catalogo')
    op.drop_table('cat_modulo_clinico', schema='gmi_catalogo')
    op.drop_table('cat_micronutriente', schema='gmi_catalogo')
    op.drop_table('cat_metodo_anticonceptivo', schema='gmi_catalogo')
    op.drop_table('cat_ips', schema='gmi_catalogo')
    op.drop_table('cat_hemoclasificacion', schema='gmi_catalogo')
    op.drop_table('cat_grupo_poblacional', schema='gmi_catalogo')
    op.drop_table('cat_estado_nutricional', schema='gmi_catalogo')
    op.drop_table('cat_especialidad', schema='gmi_catalogo')
    op.drop_table('cat_eapb', schema='gmi_catalogo')
    op.drop_table('cat_diagnostico_cie10', schema='gmi_catalogo')
    op.drop_table('rol', schema='gmi_auth')
    op.drop_table('permiso', schema='gmi_auth')
    op.drop_table('cat_categoria_educativa', schema='gmi')
    # ### end Alembic commands ###
