"""tablas iniciales: cat_modulo_clinico, rol, usuario_staff, gestante, pregunta_seguridad

Revision ID: aea61ff7bfe3
Revises: 
Create Date: 2026-03-15 09:57:06.704352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aea61ff7bfe3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='gmi_auth'
    )
    op.create_table('cat_modulo_clinico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('semana_eg_inicio', sa.Integer(), nullable=True),
    sa.Column('semana_eg_fin', sa.Integer(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='gmi_catalogo'
    )
    op.create_table('usuario_staff',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('ips_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['gmi_auth.rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='gmi_auth'
    )
    op.create_table('gestante',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_gmi', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('nacionalidad_id', sa.Integer(), nullable=True),
    sa.Column('eapb_id', sa.Integer(), nullable=True),
    sa.Column('pertenencia_etnica_id', sa.Integer(), nullable=True),
    sa.Column('grupo_poblacional_id', sa.Integer(), nullable=True),
    sa.Column('tipo_regimen', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('fecha_ultima_menstruacion', sa.Date(), nullable=False),
    sa.Column('fecha_probable_parto', sa.Date(), nullable=True),
    sa.Column('anio_ingreso', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso_cpn', sa.Date(), nullable=True),
    sa.Column('semanas_eg_ingreso', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('modulo_activo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['gmi_auth.usuario_staff.id'], ),
    sa.ForeignKeyConstraint(['modulo_activo_id'], ['gmi_catalogo.cat_modulo_clinico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_gmi'),
    schema='gmi'
    )
    op.create_table('pregunta_seguridad',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gestante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pregunta', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('hash_respuesta', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestante_id'], ['gmi.gestante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gestante_id'),
    schema='gmi'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pregunta_seguridad', schema='gmi')
    op.drop_table('gestante', schema='gmi')
    op.drop_table('usuario_staff', schema='gmi_auth')
    op.drop_table('cat_modulo_clinico', schema='gmi_catalogo')
    op.drop_table('rol', schema='gmi_auth')
    # ### end Alembic commands ###
